apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration-slack
  name: integration-slack
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: integration-slack